# Generated by Django 6.0.7 on 2026-07-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='nhis_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='nhis_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending Renewal')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='nhis_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
