# Generated by Django 6.0.7 on 2026-07-07 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('symptoms_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('checked_in', 'Checked In'), ('triaged', 'Triaged'), ('waiting', 'Waiting for Doctor'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='checked_in', max_length=20)),
                ('triage_score', models.PositiveSmallIntegerField(default=0)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='routine', max_length=20)),
                ('consultation_notes', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triage_score', 'checked_in_at'],
            },
        ),
    ]
