# Generated by Django 6.0.7 on 2026-07-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='nhis_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='pain_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='queue_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='visit',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
    ]
