# Generated by Django 6.0.7 on 2026-07-08 17:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('visits', '0002_visit_nhis_verified_visit_pain_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_on_admission', models.TextField()),
                ('admission_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='admitted', max_length=20)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_made', to=settings.AUTH_USER_MODEL)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attending_admissions', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='hospital.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visit')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='hospital.ward')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('pre_op_notes', models.TextField(blank=True)),
                ('post_op_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to=settings.AUTH_USER_MODEL)),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_performed', to=settings.AUTH_USER_MODEL)),
                ('theatre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.theatre')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visit')),
            ],
            options={
                'verbose_name_plural': 'surgeries',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
